apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: generated
    behavior: create
    envs:
      - settings.env
generatorOptions:
  disableNameSuffixHash: true
resources:
  - keeper.yaml
